<template>
  <div class="home">
    <h1>Overview of subpages</h1>
    <a href="register/">Register</a>
    <a href="login/">Login</a>
    <a href="delete/">Delete</a>
    <a href="captcha/">Captcha</a>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'HomePage',
})
</script>

<style scoped>
/* Styling partially generated by AI */
.home {
  background-color: #1a1a1a;
  font-family: monospace;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  margin: 0;
  padding: 10px;
  box-sizing: border-box;
  overflow: hidden;
}

h1 {
  color: white;
  font-size: clamp(1.2rem, 7vh, 6rem);
  text-align: center;
  margin: 0 0 4vh 0;
  text-transform: uppercase;
}

a {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 90%;
  max-width: 500px;
  height: 12vh;
  margin: 2vh 0;
  background-color: #1a1a1a;
  color: #00ff88;
  text-decoration: none;
  font-size: clamp(1.1rem, 5vh, 4rem);
  font-weight: 800;
  border: 3px solid #00ff88;
  border-radius: 12px;
  box-sizing: border-box;
  transition: all 0.2s ease;
}

a:hover {
  background-color: #00ff88;
  color: black;
}
</style>